# Connection details for solo mining
Location: [0,0]
PrimeURL: "ws://127.0.0.1:8001"
RegionURLs: ["ws://127.0.0.1:8002", "ws://127.0.0.1:8003", "ws://127.0.0.1:8004"]
ZoneURLs: [["ws://127.0.0.1:8200", "ws://127.0.0.1:8201", "ws://127.0.0.1:8202"], ["ws://127.0.0.1:8220", "ws://127.0.0.1:8221", "ws://127.0.0.1:8222"], ["ws://127.0.0.1:8240", "ws://127.0.0.1:8241", "ws://127.0.0.1:8242"] ]
RunBlake3: True
